### ISSUE TITLE
List index out of range

### ISSUE THREAD

**Issue by abconnor** [webhamster/advancedcaching#187]
Hi,

I use version 0.9.1.4 on a N900. After choosing "download overview" the error "list index out of range" occurs. Can you fix it? I love this program and it would be a pity to must give it up. Thanks for any answers.

Greetings,
Andreas

**Comment by abconnor** [comment]
To continue the description: There is also a problem when the number of caches fill more than one list. By fetching the second list the program hangs up.
The error "list index out of range" occurs not at every cache. Only some of them trigger the error and they are always the same.

**Comment by webhamster** [comment]
Is closed in latest commit. Will try to push a version to the maemo repos.
